import '@/app/[lang]/styles/globals.css';
import { Inter } from 'next/font/google';

import getCurrentUser from './actions/getCurrentUser';
import Header from './components/Header/Header';

import Providers from './providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();

  return (
    <html lang={params.lang}>
      <body className={inter.className}>
        <Providers>
          <Header currentUser={currentUser} />
          {children}
        </Providers>
      </body>
    </html>
  );
}
